---
- hosts: localhost
  tasks:
  - name: making a ssh less connection from localhost
    include_role:
      name: ssh-less
    vars:
      password: "{{ vm_password }}"
      hosts: "{{ groups['all'] }}"
      key_gen: False
    tags: always

- hosts: nodes
  tasks:
  - name: subscription manager
    include_role:
      name: redhat_subscription
    vars:
      username: "{{ subscription_username }}"
      password: "{{ subscription_password }}"
      pool_ids: "{{ subscription_pool_ids }}"
      repos: "{{ subscription_repos }}"
    when: "subscription"
    tags: subscription

  - name: yum install and update packages
    include_role:
      name: yum
    vars:
        packages: "{{ yum_packages }}"
    tags: yum

  - name: configure docker
    include_role:
      name: docker
    vars:
      device: "{{ docker_device }}"
      vg: "{{ docker_vg }}"
    when: "dockerConfig"
    tags: docker

  - name: generate ssh key and make sshless connection b/w hosts
    include_role:
      name: ssh-less
    vars:
      password: "{{ vm_password }}"
      hosts: "{{ play_hosts }}"
    when: "sshLess"
    tags: ssh

  - name: reboot nodes and wait for it to come up
    include_role:
      name: reboot-nodes 
    when: "reboot"
    tags: reboot
